//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamFoundationServerIntegrationPack {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeamFoundationServerIntegrationPack.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build definition is not found on the build server..
        /// </summary>
        internal static string BuildDefinitionNotFound {
            get {
                return ResourceManager.GetString("BuildDefinitionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build is not found on the build server..
        /// </summary>
        internal static string BuildNotFound {
            get {
                return ResourceManager.GetString("BuildNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change set is not found..
        /// </summary>
        internal static string ChangeSetNotFound {
            get {
                return ResourceManager.GetString("ChangeSetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeamFoundationServerIP Listener.
        /// </summary>
        internal static string EtwListenerName {
            get {
                return ResourceManager.GetString("EtwListenerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2FAF39E7-673B-4D89-BB89-E2CDADE0EA13}.
        /// </summary>
        internal static string EtwProviderId {
            get {
                return ResourceManager.GetString("EtwProviderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeamFoundationServerIPProvider.
        /// </summary>
        internal static string EtwProviderName {
            get {
                return ResourceManager.GetString("EtwProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create a new work item..
        /// </summary>
        internal static string FailedToCreateWorkItem {
            get {
                return ResourceManager.GetString("FailedToCreateWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get items on the version control server..
        /// </summary>
        internal static string FailedToGetItems {
            get {
                return ResourceManager.GetString("FailedToGetItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update the workspace..
        /// </summary>
        internal static string FailedToUpdateWorkspace {
            get {
                return ResourceManager.GetString("FailedToUpdateWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; = &apos;{1}&apos; cannot be found in the fields.
        /// </summary>
        internal static string FieldNotFound {
            get {
                return ResourceManager.GetString("FieldNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to validate all fields, here is the list of invalid fields: .
        /// </summary>
        internal static string InvalidFieldsList {
            get {
                return ResourceManager.GetString("InvalidFieldsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either test run ID or title must be provided.
        /// </summary>
        internal static string MissingTestRunIdOrTitle {
            get {
                return ResourceManager.GetString("MissingTestRunIdOrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one test case or test suite should be provided.
        /// </summary>
        internal static string NoTestCaseOrSuite {
            get {
                return ResourceManager.GetString("NoTestCaseOrSuite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No test run is found.
        /// </summary>
        internal static string NoTestRun {
            get {
                return ResourceManager.GetString("NoTestRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to query the work items..
        /// </summary>
        internal static string QueryFailed {
            get {
                return ResourceManager.GetString("QueryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team project is not found..
        /// </summary>
        internal static string TeamProjectNotFound {
            get {
                return ResourceManager.GetString("TeamProjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test case not found in this run.
        /// </summary>
        internal static string TestCaseNotFound {
            get {
                return ResourceManager.GetString("TestCaseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Test Configuration with given Name is not found..
        /// </summary>
        internal static string TestConfigurationNotFound {
            get {
                return ResourceManager.GetString("TestConfigurationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified Test Plan by ID/Name is not found..
        /// </summary>
        internal static string TestPlanNotFound {
            get {
                return ResourceManager.GetString("TestPlanNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TestRun with given ID is not found..
        /// </summary>
        internal static string TestRunNotFound {
            get {
                return ResourceManager.GetString("TestRunNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Version Control Server Path should not be empty..
        /// </summary>
        internal static string VersionControlServerPathShouldNotBeEmpty {
            get {
                return ResourceManager.GetString("VersionControlServerPathShouldNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Item Query should not be empty..
        /// </summary>
        internal static string WiqlShouldNotBeEmpty {
            get {
                return ResourceManager.GetString("WiqlShouldNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Item ID should be greater than 0..
        /// </summary>
        internal static string WorkItemIdShouldBeGreaterThanZero {
            get {
                return ResourceManager.GetString("WorkItemIdShouldBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work item is not found..
        /// </summary>
        internal static string WorkItemNotFound {
            get {
                return ResourceManager.GetString("WorkItemNotFound", resourceCulture);
            }
        }
    }
}
