//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsWorkflowIntegrationPack {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsWorkflowIntegrationPack.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified assembly &apos;{0}&apos; is not found..
        /// </summary>
        internal static string AssemblyFileNotFound {
            get {
                return ResourceManager.GetString("AssemblyFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified class &apos;{0}&apos; is not found in assembly &apos;{1}&apos;..
        /// </summary>
        internal static string ClassNotFoundInAssembly {
            get {
                return ResourceManager.GetString("ClassNotFoundInAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database connection must not be null for Resume Workflow.
        /// </summary>
        internal static string EmptyDatabaseConnection {
            get {
                return ResourceManager.GetString("EmptyDatabaseConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow {0} Aborted, Exception: {0}\n{1}.
        /// </summary>
        internal static string WorkflowAborted {
            get {
                return ResourceManager.GetString("WorkflowAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified workflow file &apos;{0}&apos; is not found..
        /// </summary>
        internal static string WorkflowFileNotFound {
            get {
                return ResourceManager.GetString("WorkflowFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow {0} is not found in the process..
        /// </summary>
        internal static string WorkflowNotFound {
            get {
                return ResourceManager.GetString("WorkflowNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow {0} Terminated, Exception: {0}\n{1}.
        /// </summary>
        internal static string WorkflowTerminated {
            get {
                return ResourceManager.GetString("WorkflowTerminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception occurred in workflow {0}: {1}
        ///Exception source {2} - {3}.
        /// </summary>
        internal static string WorkflowUnhandledException {
            get {
                return ResourceManager.GetString("WorkflowUnhandledException", resourceCulture);
            }
        }
    }
}
